app_id = "app_01je4dgpcyfvgrz8f1ys3pbxas"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01je4jj1tteaktf0zd0anm8854"
name = "currency-converter"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "make -j4"

  # xtp plugin init runs this script to format the plugin code
  format = "make format"

  # xtp plugin init runs this script before running the format script
  prepare = "make wasisdk"


[[test]]
name = "basic tests"
with = "../../test/testsuite/dist/test.wasm"
mock_host = "../../test/host/dist/host.wasm"