app_id = "app_01je4dgpcyfvgrz8f1ys3pbxas"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01je4jj1tteaktf0zd0anm8854"
# This is the 'binding' name used for the plugin.
name = "onedrive"

[scripts]
# xtp plugin build runs this script to generate the wasm file
build = "mkdir -p dist && tinygo build -buildmode c-shared -target wasip1 -o dist/plugin.wasm ."

# xtp plugin init runs this script to format the code
format = "go fmt && go mod tidy && goimports -w main.go"

# xtp plugin init runs this script before running the format script
prepare = "bash prepare.sh && go get ./..."
