app_id = "app_01je4dgpcyfvgrz8f1ys3pbxas"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "../../target/wasm32-wasip1/release/plugin.wasm" # when we are in a cargo workspace, bins are in root/target
extension_point_id = "ext_01je4jj1tteaktf0zd0anm8854"
# This is the 'binding' name used for the plugin.
name = "qr-code"

[scripts]
# xtp plugin build runs this script to generate the wasm file
build = "cargo build --release --target wasm32-wasip1"

# xtp plugin init runs this script to format the code
format = "cargo fmt"

# xtp plugin init runs this script before running the format script
# prepare = ""

[[test]]
name = "basic tests"
with = "../../test/testsuite/dist/test.wasm"
