app_id = "app_01je4dgpcyfvgrz8f1ys3pbxas"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01je4jj1tteaktf0zd0anm8854"
name = "tenor-gifs"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "mkdir -p dist && bash build.sh"

  # xtp plugin init runs this script to format the plugin code
  format = "go fmt && go mod tidy && goimports -w main.go"

  # xtp plugin init runs this script before running the format script
  prepare = "sh prepare.sh && go get ./..."

[[test]]
name = "basic tests"
with = "../../test/testsuite/dist/test.wasm"

[[test]]
name = "describe output"
with = "../../simulations/describe-output/dist/plugin.wasm"